### ISSUE TITLE
Error with PyAsyncCAI

### ISSUE THREAD

**Issue by Tenko-boop** [jofizcd/Soul-of-Waifu#2]
File "C:\Soul-of-Waifu-main\main_en.py", line 11, in <module>
    from characterai import PyAsyncCAI
ImportError: cannot import name 'PyAsyncCAI' from 'characterai' (C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\characterai\__init__.py)

**Comment by Viphase** [comment]
Нужна более старая версия библиотеки - pip install characterai==0.8.0
